namespace CredoCms.Application.SiteSettingsManagement;

/// <summary>Public-facing subset, returned to anonymous SPA bootstrap.
/// Phase 2 additions exposed publicly: LeadersPageLabel (used by the public
/// nav and routes), HomepageHeroCtaLabel/Link.</summary>
public sealed record PublicSiteSettingsDto(
    string ChurchName,
    string? Tagline,
    string? LogoUrl,
    string PrimaryColor,
    string AccentColor,
    string? ContactEmail,
    string? ContactPhone,
    string? ContactAddress,
    string? FacebookUrl,
    string? InstagramUrl,
    string? YouTubeUrl,
    string? XUrl,
    string? TikTokUrl,
    string? OtherSocialLabel,
    string? OtherSocialUrl,
    string? FooterText,
    string LeadersPageLabel,
    string HomepageHeroCtaLabel,
    string HomepageHeroCtaLink);

/// <summary>Full settings DTO returned to admins.</summary>
public sealed record SiteSettingsDto(
    string ChurchName,
    string? Tagline,
    string? LogoUrl,
    string PrimaryColor,
    string AccentColor,
    string? ContactEmail,
    string? ContactPhone,
    string? ContactAddress,
    string? FacebookUrl,
    string? InstagramUrl,
    string? YouTubeUrl,
    string? XUrl,
    string? TikTokUrl,
    string? OtherSocialLabel,
    string? OtherSocialUrl,
    string? FooterText,
    int DefaultVersionRetentionCount,
    string LeadersPageLabel,
    string LeaderCategoriesJson,
    string DocumentCategoriesJson,
    long MaxDocumentSizeBytes,
    long MaxImageSizeBytes,
    int ImageMaxWidth,
    int ImageQuality,
    string? MembersWelcomeText,
    string HomepageHeroCtaLabel,
    string HomepageHeroCtaLink,
    string? DefaultMetaDescription,
    DateTimeOffset CreatedAt,
    DateTimeOffset ModifiedAt,
    Guid? ModifiedByUserId,
    string RowVersion);

public sealed record UpdateSiteSettingsRequest(
    string ChurchName,
    string? Tagline,
    string? LogoUrl,
    string PrimaryColor,
    string AccentColor,
    string? ContactEmail,
    string? ContactPhone,
    string? ContactAddress,
    string? FacebookUrl,
    string? InstagramUrl,
    string? YouTubeUrl,
    string? XUrl,
    string? TikTokUrl,
    string? OtherSocialLabel,
    string? OtherSocialUrl,
    string? FooterText,
    int DefaultVersionRetentionCount,
    string LeadersPageLabel,
    string LeaderCategoriesJson,
    string DocumentCategoriesJson,
    long MaxDocumentSizeBytes,
    long MaxImageSizeBytes,
    int ImageMaxWidth,
    int ImageQuality,
    string? MembersWelcomeText,
    string HomepageHeroCtaLabel,
    string HomepageHeroCtaLink,
    string? DefaultMetaDescription,
    string RowVersion);
