using CredoCms.Domain.Email;
using CredoCms.Domain.Settings;

namespace CredoCms.Application.SiteSettingsManagement;

/// <summary>Public-facing subset, returned to anonymous SPA bootstrap.
/// Phase 2 additions exposed publicly: LeadersPageLabel (used by the public
/// nav and routes), HomepageHeroCtaLabel/Link.</summary>
public sealed record PublicSiteSettingsDto(
    string ChurchName,
    string? Tagline,
    string? LogoUrl,
    string PrimaryColor,
    string AccentColor,
    string? ContactEmail,
    string? ContactPhone,
    string? ContactAddress,
    string? FacebookUrl,
    string? InstagramUrl,
    string? YouTubeUrl,
    string? XUrl,
    string? TikTokUrl,
    string? OtherSocialLabel,
    string? OtherSocialUrl,
    string? FooterText,
    string LeadersPageLabel,
    string HomepageHeroCtaLabel,
    string HomepageHeroCtaLink,
    /// <summary>Drives whether the SPA shows the "Continue with Facebook"
    /// button on /login. Phase 4 Q15 introduced the toggle.</summary>
    bool FacebookLoginEnabled,
    // Phase 6 — analytics + cookie consent surface for the SPA bootstrap.
    /// <summary>Analytics provider. <c>None</c> hides the cookie banner.</summary>
    AnalyticsProvider AnalyticsProvider,
    /// <summary>GA4 measurement ID. The SPA only reads this after consent.</summary>
    string? Ga4MeasurementId,
    bool Ga4ConsentBannerEnabled,
    ConsentBannerPosition Ga4ConsentBannerPosition,
    /// <summary>Resolved Page slug for the consent banner's "Cookie Policy"
    /// link. Null when no page is configured.</summary>
    string? CookiePolicyPageSlug,
    /// <summary>Selects the public-facing visual template. The SPA writes
    /// <c>data-template</c> on the church theme root from this value.</summary>
    PublicTemplate Template);

/// <summary>Full settings DTO returned to admins.</summary>
public sealed record SiteSettingsDto(
    string ChurchName,
    string? Tagline,
    string? LogoUrl,
    string PrimaryColor,
    string AccentColor,
    string? ContactEmail,
    string? ContactPhone,
    string? ContactAddress,
    string? FacebookUrl,
    string? InstagramUrl,
    string? YouTubeUrl,
    string? XUrl,
    string? TikTokUrl,
    string? OtherSocialLabel,
    string? OtherSocialUrl,
    string? FooterText,
    int DefaultVersionRetentionCount,
    string LeadersPageLabel,
    string LeaderCategoriesJson,
    string DocumentCategoriesJson,
    long MaxDocumentSizeBytes,
    long MaxImageSizeBytes,
    int ImageMaxWidth,
    int ImageQuality,
    string? MembersWelcomeText,
    string HomepageHeroCtaLabel,
    string HomepageHeroCtaLink,
    string? DefaultMetaDescription,
    // ---- Phase 4 admin-side fields ---------------------------------------
    string GetInvolvedPageLabel,
    string ClassesPageLabel,
    string ClassAudienceAgeGroupsJson,
    bool ShowRecentPastOnPublicClasses,
    int RecentPastClassesLookbackDays,
    string BlogCategoriesJson,
    string BlogPageLabel,
    string? ProfanityWordlist,
    string? ProfanityAllowlist,
    int PrayerRequestArchiveDays,
    bool PrayerRequestRequireApproval,
    string ConnectCardInterestsJson,
    string? ConnectCardAcknowledgmentMessageJson,
    string ConnectCardPageLabel,
    string? CloudflareTurnstileSiteKey,
    /// <summary>Masked in the admin UI. Sent on every PUT regardless.</summary>
    string? CloudflareTurnstileSecretKey,
    string? FacebookOAuthAppId,
    /// <summary>Masked in the admin UI. Sent on every PUT regardless.</summary>
    string? FacebookOAuthAppSecret,
    bool FacebookLoginEnabled,
    // ---- Phase 5 admin-side fields ---------------------------------------
    EmailProvider EmailProvider,
    string EmailFromAddress,
    string EmailFromName,
    string? EmailReplyToAddress,
    /// <summary>Masked in the admin UI. Sent on every PUT regardless.</summary>
    string? SendGridApiKey,
    /// <summary>Masked in the admin UI. Sent on every PUT regardless.</summary>
    string? SendGridWebhookSecret,
    string? SmtpHost,
    int SmtpPort,
    string? SmtpUsername,
    /// <summary>Masked in the admin UI. Sent on every PUT regardless.</summary>
    string? SmtpPassword,
    bool SmtpUseSsl,
    bool EmailEnabled,
    string? TestEmailRecipient,
    BroadcastTargetMode NewsEmailTargetMode,
    string NewsEmailTargetGroupIdsJson,
    BroadcastTargetMode BlogEmailTargetMode,
    string BlogEmailTargetGroupIdsJson,
    string EmailSubjectPrefixNews,
    string EmailSubjectPrefixBlog,
    AdminNotificationFrequency AdminNotificationFrequency,
    SmsProvider SmsProvider,
    string? TwilioAccountSid,
    /// <summary>Masked in the admin UI. Sent on every PUT regardless.</summary>
    string? TwilioAuthToken,
    string? TwilioFromNumber,
    // ---- Phase 6 admin-side fields ---------------------------------------
    AnalyticsProvider AnalyticsProvider,
    string? Ga4MeasurementId,
    bool Ga4ConsentBannerEnabled,
    ConsentBannerPosition Ga4ConsentBannerPosition,
    Guid? CookiePolicyPageId,
    // ---- Public Site design handoff --------------------------------------
    PublicTemplate Template,
    DateTimeOffset CreatedAt,
    DateTimeOffset ModifiedAt,
    Guid? ModifiedByUserId,
    string RowVersion);

public sealed record UpdateSiteSettingsRequest(
    string ChurchName,
    string? Tagline,
    string? LogoUrl,
    string PrimaryColor,
    string AccentColor,
    string? ContactEmail,
    string? ContactPhone,
    string? ContactAddress,
    string? FacebookUrl,
    string? InstagramUrl,
    string? YouTubeUrl,
    string? XUrl,
    string? TikTokUrl,
    string? OtherSocialLabel,
    string? OtherSocialUrl,
    string? FooterText,
    int DefaultVersionRetentionCount,
    string LeadersPageLabel,
    string LeaderCategoriesJson,
    string DocumentCategoriesJson,
    long MaxDocumentSizeBytes,
    long MaxImageSizeBytes,
    int ImageMaxWidth,
    int ImageQuality,
    string? MembersWelcomeText,
    string HomepageHeroCtaLabel,
    string HomepageHeroCtaLink,
    string? DefaultMetaDescription,
    // ---- Phase 4 admin-side fields ---------------------------------------
    string GetInvolvedPageLabel,
    string ClassesPageLabel,
    string ClassAudienceAgeGroupsJson,
    bool ShowRecentPastOnPublicClasses,
    int RecentPastClassesLookbackDays,
    string BlogCategoriesJson,
    string BlogPageLabel,
    string? ProfanityWordlist,
    string? ProfanityAllowlist,
    int PrayerRequestArchiveDays,
    bool PrayerRequestRequireApproval,
    string ConnectCardInterestsJson,
    string? ConnectCardAcknowledgmentMessageJson,
    string ConnectCardPageLabel,
    string? CloudflareTurnstileSiteKey,
    string? CloudflareTurnstileSecretKey,
    string? FacebookOAuthAppId,
    string? FacebookOAuthAppSecret,
    bool FacebookLoginEnabled,
    // ---- Phase 5 admin-side fields ---------------------------------------
    EmailProvider EmailProvider,
    string EmailFromAddress,
    string EmailFromName,
    string? EmailReplyToAddress,
    string? SendGridApiKey,
    string? SendGridWebhookSecret,
    string? SmtpHost,
    int SmtpPort,
    string? SmtpUsername,
    string? SmtpPassword,
    bool SmtpUseSsl,
    bool EmailEnabled,
    string? TestEmailRecipient,
    BroadcastTargetMode NewsEmailTargetMode,
    string NewsEmailTargetGroupIdsJson,
    BroadcastTargetMode BlogEmailTargetMode,
    string BlogEmailTargetGroupIdsJson,
    string EmailSubjectPrefixNews,
    string EmailSubjectPrefixBlog,
    AdminNotificationFrequency AdminNotificationFrequency,
    SmsProvider SmsProvider,
    string? TwilioAccountSid,
    string? TwilioAuthToken,
    string? TwilioFromNumber,
    // ---- Phase 6 admin-side fields ---------------------------------------
    AnalyticsProvider AnalyticsProvider,
    string? Ga4MeasurementId,
    bool Ga4ConsentBannerEnabled,
    ConsentBannerPosition Ga4ConsentBannerPosition,
    Guid? CookiePolicyPageId,
    // ---- Public Site design handoff --------------------------------------
    PublicTemplate Template,
    string RowVersion);
