namespace CredoCms.Application.SiteSettingsManagement;

/// <summary>Public-facing subset, returned to anonymous SPA bootstrap.
/// Phase 2 additions exposed publicly: LeadersPageLabel (used by the public
/// nav and routes), HomepageHeroCtaLabel/Link.</summary>
public sealed record PublicSiteSettingsDto(
    string ChurchName,
    string? Tagline,
    string? LogoUrl,
    string PrimaryColor,
    string AccentColor,
    string? ContactEmail,
    string? ContactPhone,
    string? ContactAddress,
    string? FacebookUrl,
    string? InstagramUrl,
    string? YouTubeUrl,
    string? XUrl,
    string? TikTokUrl,
    string? OtherSocialLabel,
    string? OtherSocialUrl,
    string? FooterText,
    string LeadersPageLabel,
    string HomepageHeroCtaLabel,
    string HomepageHeroCtaLink,
    /// <summary>Drives whether the SPA shows the "Continue with Facebook"
    /// button on /login. Phase 4 Q15 introduced the toggle.</summary>
    bool FacebookLoginEnabled);

/// <summary>Full settings DTO returned to admins.</summary>
public sealed record SiteSettingsDto(
    string ChurchName,
    string? Tagline,
    string? LogoUrl,
    string PrimaryColor,
    string AccentColor,
    string? ContactEmail,
    string? ContactPhone,
    string? ContactAddress,
    string? FacebookUrl,
    string? InstagramUrl,
    string? YouTubeUrl,
    string? XUrl,
    string? TikTokUrl,
    string? OtherSocialLabel,
    string? OtherSocialUrl,
    string? FooterText,
    int DefaultVersionRetentionCount,
    string LeadersPageLabel,
    string LeaderCategoriesJson,
    string DocumentCategoriesJson,
    long MaxDocumentSizeBytes,
    long MaxImageSizeBytes,
    int ImageMaxWidth,
    int ImageQuality,
    string? MembersWelcomeText,
    string HomepageHeroCtaLabel,
    string HomepageHeroCtaLink,
    string? DefaultMetaDescription,
    // ---- Phase 4 admin-side fields ---------------------------------------
    string GetInvolvedPageLabel,
    string ClassesPageLabel,
    string ClassAudienceAgeGroupsJson,
    bool ShowRecentPastOnPublicClasses,
    int RecentPastClassesLookbackDays,
    string BlogCategoriesJson,
    string BlogPageLabel,
    string? ProfanityWordlist,
    string? ProfanityAllowlist,
    int PrayerRequestArchiveDays,
    bool PrayerRequestRequireApproval,
    string ConnectCardInterestsJson,
    string? ConnectCardAcknowledgmentMessageJson,
    string ConnectCardPageLabel,
    string? CloudflareTurnstileSiteKey,
    /// <summary>Masked in the admin UI. Sent on every PUT regardless.</summary>
    string? CloudflareTurnstileSecretKey,
    string? FacebookOAuthAppId,
    /// <summary>Masked in the admin UI. Sent on every PUT regardless.</summary>
    string? FacebookOAuthAppSecret,
    bool FacebookLoginEnabled,
    DateTimeOffset CreatedAt,
    DateTimeOffset ModifiedAt,
    Guid? ModifiedByUserId,
    string RowVersion);

public sealed record UpdateSiteSettingsRequest(
    string ChurchName,
    string? Tagline,
    string? LogoUrl,
    string PrimaryColor,
    string AccentColor,
    string? ContactEmail,
    string? ContactPhone,
    string? ContactAddress,
    string? FacebookUrl,
    string? InstagramUrl,
    string? YouTubeUrl,
    string? XUrl,
    string? TikTokUrl,
    string? OtherSocialLabel,
    string? OtherSocialUrl,
    string? FooterText,
    int DefaultVersionRetentionCount,
    string LeadersPageLabel,
    string LeaderCategoriesJson,
    string DocumentCategoriesJson,
    long MaxDocumentSizeBytes,
    long MaxImageSizeBytes,
    int ImageMaxWidth,
    int ImageQuality,
    string? MembersWelcomeText,
    string HomepageHeroCtaLabel,
    string HomepageHeroCtaLink,
    string? DefaultMetaDescription,
    // ---- Phase 4 admin-side fields ---------------------------------------
    string GetInvolvedPageLabel,
    string ClassesPageLabel,
    string ClassAudienceAgeGroupsJson,
    bool ShowRecentPastOnPublicClasses,
    int RecentPastClassesLookbackDays,
    string BlogCategoriesJson,
    string BlogPageLabel,
    string? ProfanityWordlist,
    string? ProfanityAllowlist,
    int PrayerRequestArchiveDays,
    bool PrayerRequestRequireApproval,
    string ConnectCardInterestsJson,
    string? ConnectCardAcknowledgmentMessageJson,
    string ConnectCardPageLabel,
    string? CloudflareTurnstileSiteKey,
    string? CloudflareTurnstileSecretKey,
    string? FacebookOAuthAppId,
    string? FacebookOAuthAppSecret,
    bool FacebookLoginEnabled,
    string RowVersion);
