import { useEffect, useMemo, useRef, useState } from "react";
import { Plus, Pencil, AlertTriangle, ChevronDown, Mail, X } from "lucide-react";
import { ResponsiveTable, type ColumnDef } from "@/components/shared/ResponsiveTable";
import { usersApi, type UserListQuery } from "@/lib/api/users";
import type { CreateUserRequest, Role, UpdateUserRequest, UserDetail, UserListItem } from "@/types/api";
import {
  Avatar,
  BigNum,
  Btn,
  Chip,
  PageHeader,
  SectionHead,
} from "@/components/shared/admin/EditorialPrimitives";
import { useToast } from "@/components/shared/admin/Toast";

const ROLE_OPTIONS: Role[] = ["Administrator", "Editor", "Member"];

export function UsersPage() {
  const [users, setUsers] = useState<UserListItem[]>([]);
  const [loading, setLoading] = useState(true);
  const [filterRole, setFilterRole] = useState<Role | "">("");
  const [filterActive, setFilterActive] = useState<"" | "active" | "deactivated">("");
  const [createOpen, setCreateOpen] = useState(false);
  const [editing, setEditing] = useState<UserListItem | null>(null);
  const [error, setError] = useState<string | null>(null);

  async function load() {
    setLoading(true);
    setError(null);
    try {
      const query: UserListQuery = {};
      if (filterRole) query.role = filterRole;
      if (filterActive) query.isActive = filterActive === "active";
      const result = await usersApi.list(query);
      setUsers(result.items);
    } catch (e: unknown) {
      setError(e instanceof Error ? e.message : "Failed to load users.");
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => {
    load();
  }, [filterRole, filterActive]);

  const columns: ColumnDef<UserListItem>[] = [
    {
      id: "name",
      header: "Person",
      accessor: (u) => (
        <div className="flex items-center gap-3">
          <Avatar name={u.displayName} size="sm" tone={u.roles.includes("Administrator") ? "accent" : "muted"} />
          <div className="min-w-0">
            <p className="truncate font-medium">{u.displayName}</p>
            <p className="truncate font-mono text-[11px] text-muted">{u.email}</p>
          </div>
        </div>
      ),
      mobilePriority: 1,
      sortBy: (u) => u.lastName,
    },
    {
      id: "roles",
      header: "Role",
      accessor: (u) => (
        <div className="flex flex-wrap gap-1">
          {u.roles.length === 0 ? (
            <span className="text-muted">—</span>
          ) : (
            u.roles.map((r) => (
              <Chip
                key={r}
                tone={r === "Administrator" ? "accent" : r === "Editor" ? "success" : "muted"}
              >
                {r}
              </Chip>
            ))
          )}
        </div>
      ),
      mobilePriority: 3,
    },
    {
      id: "status",
      header: "Status",
      accessor: (u) =>
        u.isActive
          ? <Chip tone="success" dot>Active</Chip>
          : <Chip tone="warn" dot>Deactivated</Chip>,
      mobilePriority: 4,
    },
    {
      id: "lastLogin",
      header: "Last active",
      accessor: (u) => (
        <span className="font-mono text-xs tabular-nums">
          {u.lastLoginAt ? new Date(u.lastLoginAt).toLocaleDateString() : "—"}
        </span>
      ),
    },
    {
      id: "actions",
      header: "Actions",
      // Right-align the th's header text AND the cell content. The th gets
      // text-right; the inner <button> (sort toggle generated by
      // ResponsiveTable) is forced inline so the alignment takes effect.
      className: "text-right [&>button]:inline-flex",
      accessor: (u) => (
        <div className="flex justify-end">
          <Btn
            size="sm"
            variant="ghost"
            iconLeft={<Pencil aria-hidden="true" strokeWidth={1.75} className="h-3.5 w-3.5" />}
            onClick={() => setEditing(u)}
          >
            Edit
          </Btn>
        </div>
      ),
      mobilePriority: 2,
    },
  ];

  const roleCounts = useMemo(() => {
    const counts: Record<string, number> = { Administrator: 0, Editor: 0, Member: 0, Other: 0 };
    for (const u of users) {
      if (u.roles.length === 0) counts.Other += 1;
      for (const r of u.roles) counts[r] = (counts[r] ?? 0) + 1;
    }
    return counts;
  }, [users]);

  const ROLE_DESCRIPTIONS: Record<Role, string> = {
    Administrator: "Full access to settings, users, and content.",
    Editor: "Compose and publish content. No user management.",
    Member: "Read members-only content; no editing rights.",
  };

  return (
    <div className="space-y-8">
      <PageHeader
        eyebrow={`${users.length} accounts`}
        title="Users"
        kicker="staff & members with sign-in access"
        actions={
          <Btn
            variant="accent"
            size="lg"
            iconLeft={<Plus className="h-4 w-4" />}
            onClick={() => setCreateOpen(true)}
          >
            Invite Member
          </Btn>
        }
      />

      <section className="space-y-4">
        <SectionHead number="01" title="Roles in use" />
        <div className="grid grid-cols-1 gap-3 sm:grid-cols-3">
          {ROLE_OPTIONS.map((r, i) => {
            const isOwner = r === "Administrator";
            return (
              <article
                key={r}
                className="relative border border-border bg-panel p-5"
              >
                {isOwner && (
                  <span aria-hidden className="absolute inset-y-0 left-0 w-[3px] bg-accent" />
                )}
                <p className="text-[11px] font-semibold uppercase tracking-[0.16em] text-muted">
                  Role {String(i + 1).padStart(2, "0")}
                </p>
                <h3 className="mt-1 font-heading text-lg font-semibold">{r}</h3>
                <BigNum size="md" className="mt-3">
                  {String(roleCounts[r] ?? 0).padStart(2, "0")}
                </BigNum>
                <p className="mt-3 text-xs text-fg-soft">{ROLE_DESCRIPTIONS[r]}</p>
              </article>
            );
          })}
        </div>
      </section>

      <section className="space-y-4">
        <SectionHead
          number="02"
          title="Members"
          right={
            <div className="flex flex-wrap items-center gap-2">
              <SelectMenu
                ariaLabel="Filter by role"
                value={filterRole}
                onChange={(v) => setFilterRole(v as Role | "")}
                options={[
                  { value: "", label: "All roles" },
                  ...ROLE_OPTIONS.map((r) => ({ value: r, label: r })),
                ]}
              />
              <SelectMenu
                ariaLabel="Filter by status"
                value={filterActive}
                onChange={(v) => setFilterActive(v as "" | "active" | "deactivated")}
                options={[
                  { value: "", label: "All statuses" },
                  { value: "active", label: "Active" },
                  { value: "deactivated", label: "Deactivated" },
                ]}
              />
            </div>
          }
        />

        {error && (
          <div role="alert" className="border border-danger/30 bg-danger/10 p-3 text-sm text-danger">
            {error}
          </div>
        )}

        {loading ? (
          <p className="text-muted">Loading…</p>
        ) : (
          <ResponsiveTable
            data={users}
            columns={columns}
            rowKey={(u) => u.id}
            searchPlaceholder="Search name or email…"
            emptyMessage="No users match your filters."
          />
        )}
      </section>

      {createOpen && <CreateUserDialog onClose={() => setCreateOpen(false)} onCreated={() => { setCreateOpen(false); load(); }} />}
      {editing && (
        <EditUserDialog
          user={editing}
          onClose={() => setEditing(null)}
          onSaved={() => { setEditing(null); load(); }}
        />
      )}
    </div>
  );
}

function CreateUserDialog({
  onClose,
  onCreated,
}: {
  onClose: () => void;
  onCreated: (user: UserDetail) => void;
}) {
  const [email, setEmail] = useState("");
  const [firstName, setFirstName] = useState("");
  const [lastName, setLastName] = useState("");
  const [roles, setRoles] = useState<Role[]>(["Member"]);
  const [sendInvitation, setSendInvitation] = useState(true);
  const [errors, setErrors] = useState<string[]>([]);
  const [submitting, setSubmitting] = useState(false);

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    setSubmitting(true);
    setErrors([]);
    try {
      const req: CreateUserRequest = { email, firstName, lastName, roles, sendInvitation };
      const created = await usersApi.create(req);
      onCreated(created);
    } catch (err) {
      const messages =
        typeof err === "object" && err !== null && "getMessages" in err
          ? (err as { getMessages: () => string[] }).getMessages()
          : ["Failed to create user."];
      setErrors(messages);
    } finally {
      setSubmitting(false);
    }
  }

  return (
    <div role="dialog" aria-modal="true" className="fixed inset-0 z-40 flex items-center justify-center bg-foreground/40 p-4">
      <form onSubmit={handleSubmit} className="w-full max-w-lg space-y-4 rounded-lg bg-background p-6 shadow-xl">
        <h2 className="text-lg font-semibold">Create user</h2>

        {errors.length > 0 && (
          <div role="alert" className="rounded-md border border-danger/30 bg-danger/10 p-3 text-sm text-danger">
            <ul className="list-disc pl-5">
              {errors.map((err) => <li key={err}>{err}</li>)}
            </ul>
          </div>
        )}

        <div className="grid grid-cols-1 gap-3 sm:grid-cols-2">
          <div>
            <label htmlFor="firstName" className="mb-1 block text-sm font-medium">First name</label>
            <input id="firstName" required value={firstName} onChange={(e) => setFirstName(e.target.value)} className="h-10 w-full rounded-md border border-input bg-background px-3 text-sm" />
          </div>
          <div>
            <label htmlFor="lastName" className="mb-1 block text-sm font-medium">Last name</label>
            <input id="lastName" required value={lastName} onChange={(e) => setLastName(e.target.value)} className="h-10 w-full rounded-md border border-input bg-background px-3 text-sm" />
          </div>
        </div>

        <div>
          <label htmlFor="email" className="mb-1 block text-sm font-medium">Email</label>
          <input id="email" required type="email" value={email} onChange={(e) => setEmail(e.target.value)} className="h-10 w-full rounded-md border border-input bg-background px-3 text-sm" />
        </div>

        <fieldset>
          <legend className="mb-1 block text-sm font-medium">Roles</legend>
          <div className="flex flex-wrap gap-3">
            {ROLE_OPTIONS.map((role) => (
              <label key={role} className="flex items-center gap-2 text-sm">
                <input
                  type="checkbox"
                  checked={roles.includes(role)}
                  onChange={(e) => setRoles((prev) => e.target.checked ? [...prev, role] : prev.filter((r) => r !== role))}
                />
                {role}
              </label>
            ))}
          </div>
        </fieldset>

        <label className="flex items-center gap-2 text-sm">
          <input type="checkbox" checked={sendInvitation} onChange={(e) => setSendInvitation(e.target.checked)} />
          Send invitation email
        </label>

        <div className="flex flex-col-reverse gap-2 sm:flex-row sm:justify-end">
          <button type="button" onClick={onClose} className="inline-flex h-10 items-center justify-center rounded-md border bg-background px-4 text-sm">Cancel</button>
          <button type="submit" disabled={submitting} className="inline-flex h-10 items-center justify-center rounded-md bg-primary px-4 text-sm font-semibold text-primary-foreground hover:bg-primary/90 disabled:opacity-50">
            {submitting ? "Creating…" : "Create user"}
          </button>
        </div>
      </form>
    </div>
  );
}

/**
 * Edit-existing-user dialog. Pre-populates from the row data, lets an
 * Administrator change name, email, role membership, and active state.
 *
 * The flag-yellow callout fires the moment the admin tries to elevate a
 * user who currently holds the Member role only (no Editor/Administrator)
 * to either of those higher-privilege roles. The warning explains exactly
 * what they're granting — Editor publishes content, Administrator can
 * change every site setting. The save still proceeds; the warning is a
 * "look twice before you click" cue, not a block.
 */
function EditUserDialog({
  user,
  onClose,
  onSaved,
}: {
  user: UserListItem;
  onClose: () => void;
  onSaved: (user: UserDetail) => void;
}) {
  const { toast } = useToast();
  const [email, setEmail] = useState(user.email);
  const [firstName, setFirstName] = useState(user.firstName);
  const [lastName, setLastName] = useState(user.lastName);
  const [roles, setRoles] = useState<Role[]>(user.roles);
  const [isActive, setIsActive] = useState(user.isActive);
  const [errors, setErrors] = useState<string[]>([]);
  const [submitting, setSubmitting] = useState(false);
  const [resending, setResending] = useState(false);

  // Member-only → privileged: the warning fires when the original record
  // is a plain Member (no other roles) and the next selection adds Editor
  // or Administrator. Re-saving a user who already has those roles does
  // NOT trigger the warning — only the actual promotion does.
  const wasMemberOnly = user.roles.length === 1 && user.roles[0] === "Member";
  const willHavePrivileged = roles.some((r) => r === "Editor" || r === "Administrator");
  const showPromotionWarning = wasMemberOnly && willHavePrivileged;

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    setSubmitting(true);
    setErrors([]);
    try {
      const req: UpdateUserRequest = { email, firstName, lastName, roles, isActive };
      const updated = await usersApi.update(user.id, req);
      onSaved(updated);
    } catch (err) {
      const messages =
        typeof err === "object" && err !== null && "getMessages" in err
          ? (err as { getMessages: () => string[] }).getMessages()
          : ["Failed to update user."];
      setErrors(messages);
    } finally {
      setSubmitting(false);
    }
  }

  async function handleResendInvitation() {
    setResending(true);
    try {
      await usersApi.resendInvitation(user.id);
      toast("success", `Invitation re-sent to ${user.email}.`);
    } catch (err) {
      const message =
        typeof err === "object" && err !== null && "getMessages" in err
          ? (err as { getMessages: () => string[] }).getMessages()[0]
          : "Could not resend invitation.";
      toast("error", message);
    } finally {
      setResending(false);
    }
  }

  return (
    <div role="dialog" aria-modal="true" aria-labelledby="edit-user-title" className="fixed inset-0 z-40 flex items-center justify-center bg-foreground/40 p-4">
      <form onSubmit={handleSubmit} className="w-full max-w-lg space-y-4 rounded-lg bg-background p-6 shadow-xl">
        <header className="space-y-1">
          <div className="flex items-start justify-between gap-3">
            <h2 id="edit-user-title" className="text-lg font-semibold">Edit user</h2>
            <button
              type="button"
              onClick={onClose}
              aria-label="Close"
              className="-mr-1 -mt-1 flex h-8 w-8 shrink-0 items-center justify-center rounded-md text-muted hover:bg-panel-alt hover:text-foreground"
            >
              <X aria-hidden="true" strokeWidth={1.75} className="h-4 w-4" />
            </button>
          </div>
          <p className="font-mono text-[11px] text-muted">{user.email}</p>
        </header>

        {errors.length > 0 && (
          <div role="alert" className="rounded-md border border-danger/30 bg-danger/10 p-3 text-sm text-danger">
            <ul className="list-disc pl-5">
              {errors.map((err) => <li key={err}>{err}</li>)}
            </ul>
          </div>
        )}

        <div className="grid grid-cols-1 gap-3 sm:grid-cols-2">
          <div>
            <label htmlFor="edit-firstName" className="mb-1 block text-sm font-medium">First name</label>
            <input id="edit-firstName" required value={firstName} onChange={(e) => setFirstName(e.target.value)} className="h-10 w-full rounded-md border border-input bg-background px-3 text-sm" />
          </div>
          <div>
            <label htmlFor="edit-lastName" className="mb-1 block text-sm font-medium">Last name</label>
            <input id="edit-lastName" required value={lastName} onChange={(e) => setLastName(e.target.value)} className="h-10 w-full rounded-md border border-input bg-background px-3 text-sm" />
          </div>
        </div>

        <div>
          <label htmlFor="edit-email" className="mb-1 block text-sm font-medium">Email</label>
          <input id="edit-email" required type="email" value={email} onChange={(e) => setEmail(e.target.value)} className="h-10 w-full rounded-md border border-input bg-background px-3 text-sm" />
        </div>

        <fieldset>
          <legend className="mb-1 block text-sm font-medium">Roles</legend>
          <div className="space-y-2">
            {ROLE_OPTIONS.map((role) => (
              <label key={role} className="flex items-start gap-2 text-sm">
                <input
                  type="checkbox"
                  checked={roles.includes(role)}
                  onChange={(e) => setRoles((prev) => e.target.checked ? [...prev, role] : prev.filter((r) => r !== role))}
                  className="mt-1"
                />
                <span>
                  <span className="font-medium">{role}</span>
                  <span className="block text-xs text-muted">{ROLE_HINTS[role]}</span>
                </span>
              </label>
            ))}
          </div>
        </fieldset>

        {showPromotionWarning && (
          <div role="alert" className="flex items-start gap-3 border border-warn/40 bg-warn/10 p-3 text-sm">
            <AlertTriangle aria-hidden="true" strokeWidth={1.75} className="mt-0.5 h-4 w-4 shrink-0 text-warn" />
            <div className="space-y-1">
              <p className="font-semibold text-warn">Promoting a member to an editing role</p>
              <p className="text-xs text-fg-soft">
                {roles.includes("Administrator")
                  ? "Administrator can change every site setting, manage users, and publish or delete content. Only grant this to someone who actively maintains the site."
                  : "Editor can compose and publish pages, news, and sermons across the site. Make sure this person should be authoring on behalf of the church."}
              </p>
            </div>
          </div>
        )}

        <label className="flex items-center gap-2 text-sm">
          <input type="checkbox" checked={isActive} onChange={(e) => setIsActive(e.target.checked)} />
          Account active (uncheck to deactivate)
        </label>

        <div className="flex flex-col-reverse gap-2 sm:flex-row sm:items-center sm:justify-between">
          {!user.emailConfirmed ? (
            <button
              type="button"
              onClick={handleResendInvitation}
              disabled={resending || submitting}
              className="inline-flex h-10 items-center justify-center gap-2 rounded-md border bg-background px-4 text-sm font-medium hover:bg-panel-alt disabled:opacity-50"
              title="Generate a fresh invitation token and re-send the welcome email to this user."
            >
              <Mail aria-hidden="true" strokeWidth={1.75} className="h-4 w-4" />
              {resending ? "Sending…" : "Resend invitation"}
            </button>
          ) : (
            <span className="hidden sm:block" aria-hidden="true" />
          )}
          <div className="flex flex-col-reverse gap-2 sm:flex-row sm:justify-end">
            <button type="button" onClick={onClose} className="inline-flex h-10 items-center justify-center rounded-md border bg-background px-4 text-sm">Cancel</button>
            <button type="submit" disabled={submitting} className="inline-flex h-10 items-center justify-center rounded-md bg-primary px-4 text-sm font-semibold text-primary-foreground hover:bg-primary/90 disabled:opacity-50">
              {submitting ? "Saving…" : "Save changes"}
            </button>
          </div>
        </div>
      </form>
    </div>
  );
}

const ROLE_HINTS: Record<Role, string> = {
  Administrator: "Full access to settings, users, and content.",
  Editor: "Compose and publish content. No user management.",
  Member: "Read-only access to members-only content.",
};

/**
 * Lightweight custom dropdown. Replaces `<select>` here because the native
 * select's option panel is rendered by the OS/browser shell and ignores
 * border-radius — even with the global `border-radius: 0 !important` rule,
 * the dropdown popup arrives with rounded Fluent corners. This component
 * paints the popup as plain DOM so the editorial square-corner rule wins.
 *
 * Behavior matches a native select closely: arrow-key navigation, Enter to
 * confirm, Esc to close, click-outside dismisses. Trigger and options share
 * the existing h-8 / border / panel-alt visual treatment.
 */
function SelectMenu({
  value,
  options,
  onChange,
  ariaLabel,
}: {
  value: string;
  options: { value: string; label: string }[];
  onChange: (value: string) => void;
  ariaLabel: string;
}) {
  const [open, setOpen] = useState(false);
  const wrapRef = useRef<HTMLDivElement>(null);
  const current = options.find((o) => o.value === value) ?? options[0];

  // Click-outside closes the popup.
  useEffect(() => {
    if (!open) return;
    const handler = (e: MouseEvent) => {
      if (wrapRef.current && !wrapRef.current.contains(e.target as Node)) {
        setOpen(false);
      }
    };
    document.addEventListener("mousedown", handler);
    return () => document.removeEventListener("mousedown", handler);
  }, [open]);

  return (
    <div ref={wrapRef} className="relative">
      <button
        type="button"
        aria-label={ariaLabel}
        aria-haspopup="listbox"
        aria-expanded={open}
        onClick={() => setOpen((v) => !v)}
        onKeyDown={(e) => {
          if (e.key === "Escape") setOpen(false);
          if (e.key === "Enter" || e.key === " " || e.key === "ArrowDown") {
            e.preventDefault();
            setOpen(true);
          }
        }}
        className="inline-flex h-8 items-center gap-2 border border-border bg-background px-3 text-xs hover:bg-panel-alt focus-visible:border-accent focus-visible:outline-none"
      >
        <span>{current.label}</span>
        <ChevronDown aria-hidden="true" strokeWidth={1.75} className="h-3.5 w-3.5 text-muted" />
      </button>
      {open && (
        <div
          role="listbox"
          aria-label={ariaLabel}
          className="absolute left-0 top-full z-30 mt-1 min-w-full border border-border bg-popover py-1 shadow-lg"
        >
          {options.map((opt) => {
            const selected = opt.value === value;
            return (
              <button
                key={opt.value}
                type="button"
                role="option"
                aria-selected={selected ? "true" : "false"}
                onClick={() => { onChange(opt.value); setOpen(false); }}
                className={`flex w-full items-center justify-between gap-3 px-3 py-1.5 text-left text-xs hover:bg-panel-alt ${selected ? "font-semibold text-foreground" : "text-fg-soft"}`}
              >
                <span>{opt.label}</span>
                {selected && <span aria-hidden="true" className="text-accent">•</span>}
              </button>
            );
          })}
        </div>
      )}
    </div>
  );
}
